### ISSUE TITLE
Hacer cambios en back para gestionar varios escape room

### ISSUE THREAD

**Issue by mmarbonillo** [mmarbonillo/celia-tour#146]
En vista de que ahora tenemos una tabla que nos permite tener varios escape room, hay que modificar la administración ya existente para que tenga en cuenta si está en un escape room o en otro

**Comment by 7-carmen** [comment]
Campos hidden necesarios añadidos por Maria y hechos los cambios necesarios en los JS y controladores para guardarlos hechos por Carmen.
Issue lista
