### ISSUE TITLE
Admin usuarios: no permite modificar usuarios

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#174]
La aplicación falla al intentar modificar los datos de un usuario existente.
Al intentar modificar la contraseña, siempre da el error "La contraseña debe tener al menos 8 caracteres..." y bla, bla, bla
Según reporta Félix, tampoco deja cambiar el nombre de usuario ni el email.

**Comment by AlejandroClares** [comment]
He mejorado la validación al modificar un usuario, que permitía guardar la contraseña saltándose el proceso de validación

Ahora también se limpian los campos de las contraseña, que se ocultaban, pero al intentar guardar pedía las verificaciones de la contraseña si no se estaban en blanco
