### ISSUE TITLE
Tabla "Opciones": espacio insuficiente para "Historia"

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#176]
La "Historia" que se introduce como un registro en la tabla opciones está muy limitada en tamaño: en cuanto quieres escribir un texto un poco largo, la aplicación da un error SQL porque falla el update (el campo se desborda)

Habría que ampliar el tamaño de ese campo. Ampliarlo mucho. Sed generosos, que los varchar no consumen los caracteres que no se emplean.

IMPORTANTE: hay que construir la migración comprobando que al lanzarla, **no se pierdan los datos previos que ya pudieran existir** en el registro "historia" de la tabla de opciones.

**Comment by angelsalascalvo** [comment]
El campo ha sido aumentado hasta un tamaño de 21000 bytes ya que es el máximo permitido para un campo string _(varchar en sql)_ en laravel.

Si sigue siendo demasiado pequeño se debería contemplar la posibilidad de cambiar el tipo de columna de la tabla a LongText (4GB de tamaño máximo) aunque al ser una columna empleada para todas las opciones, podría afectar a la velocidad de recuperación del resto de registros de dicha tabla.

@avozme
