### ISSUE TITLE
Añadir, modificar y eliminar escenas desde mapa de zona

### ISSUE THREAD

**Issue by mmarbonillo** [mmarbonillo/celia-tour#29]
* Añadir puntos al mapa de una zona y asignarle una escena.
* Modificar los puntos del mapa y el nombre e imagen de la escena asociada.
* Eliminar los puntos del mapa así como la escena que tenga asociada.

**Comment by avozme** [comment]
Adjunto mapa del sótano
![sotano](https://user-images.githubusercontent.com/25744642/74331096-37ce0000-4d93-11ea-81ad-983806e3646b.png)
