### ISSUE TITLE
Subir escenas: Versión Linux de krpano

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#51]
Hay que añadir la versión para Linux de krpano.

También hay que decidir si se ejecuta una versión u otra del programa, dependiendo de una variable de entorno que debe agregarse al archivo .env

Por último, al subir una escena, hay que mejorar la apariencia y la información del mensaje de error en caso de que falle la subida.

**Comment by avozme** [comment]
El comando para que funcione en sistemas Linux es el siguiente (línea 70 del archivo SceneController.php):

`$process = new Process(['./krpano/krpanotools', 'makepano', '-config=config', $image]);`

**Comment by mmarbonillo** [comment]
krpanotools register KStS7s75sRvUsZosTTCUQw6omSSOfyTMJ00EdO2SpkUU64s7cI23QRESjo/V5Vst4+zkKabeNX7Cp3dDXzx8ZAJZFGa2l/IYWP2ToWFrafYPEWnKzfmPkmmkz5ehAf8JqQOwqVTu64Fq7kTNBgXRvPjrJobXMgbJzT2eKBCoICEZkcBcea8wn0WBf4PCWoKfTk01OI06RwNrhrXO4TPUltQUO80KQVchRqw2YEPs0AHr2yrRyQ==
