### ISSUE TITLE
Bugs Jose

### ISSUE THREAD

**Issue by 7-carmen** [mmarbonillo/celia-tour#60]
1º Añadir ventana modal de confirmación de Eliminar en los portkey
2º Añadir ventana modal de confirmación de Eliminar en los porkey scene

**Comment by 7-carmen** [comment]
BUGS EN EL DESPLEGADO: 
1. El modificar transladores no deja seleccionar escena
2. No funciona el eliminar de los transladores.

**Comment by 7-carmen** [comment]
No funciona el botón de cerrar ventana modal en el editar translador

**Comment by Jose-bousfanj-95** [comment]
Que no sabia como se cerraban issues y esto ya estaba completado hace tiempo
