### ISSUE TITLE
Bugs Angel

### ISSUE THREAD

**Issue by 7-carmen** [mmarbonillo/celia-tour#62]
1º Añadir la ventana modal de confirmar Eliminar en los hostpod

**Comment by 7-carmen** [comment]
1. Agregar la opción de elegir el icono de la pestaña del navegador e implementarla.

**Comment by angelsalascalvo** [comment]
- Botón desplazamiento entre plantas del mapa no funciona al llegar al extremo inferior.
- Agregar botón "Cancelar" en la creación de un nuevo hotspot.
- Agregar metadescripcion y metatitulo de la tabla de opciones en el layout principal.
- Obtener correctamente el orden de los puntos destacados en el frontend

**Comment by angelsalascalvo** [comment]
Bugs solucionados hasta el momento
