### ISSUE TITLE
Añadir descripción a previsualizaciones de recursos de audio

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#70]
Los recursos de audio aparecen en varios puntos del panel de administración como un espectro de frecuencias. Sería interesante añadir a ese icono el título del recurso para distinguir de un solo vistazo unos audios de otros.

**Comment by angelsalascalvo** [comment]
Como solución se ha implementado un texto de tipo tooltip / alt con la descripción que aparece al pasar con el ratón sobre el recurso, ya que el texto directamente sobre la miniatura no quedaba estéticamente bien.

![image](https://user-images.githubusercontent.com/34268023/77171625-0bf21880-6abd-11ea-8a28-53937d578c7e.png)
