### ISSUE TITLE
Video sigue reproduciéndose fuera de pantalla

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#74]
En la visita libre, cuando hay un vídeo, desaparece de la imagen cuando nos movemos hacia otro lado, pero el audio sigue oyéndose.

Hay varias soluciones posibles:
- Deshabilitar el movimiento de la cámara mientras el vídeo se está reproduciendo.
- Hacer que el vídeo permanezca siempre en el centro de la pantalla, aunque movamos la cámara, hasta que lo cerremos.
- Detener la reproducción cuando movemos la cámara.

**Comment by angelsalascalvo** [comment]
Resuelto.
Para solucionar el bug se ha cambiado la visualización del vídeo haciéndose de forma modal (en frontend). Actualmente, mientras se reproduce el vídeo no se puede navegar por la imagen 360, es necesario cerrar la modal para ello.
