### ISSUE TITLE
Añadir posibilidad de un homepage estático

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#81]
Vamos a volver a ofrecer la posibilidad de que la imagen del home sea una imagen estática, no una escena 360.

Esto es debido a que a veces no tendremos ninguna escena 360 lo bastante espectacular como para usarla en el home.

Los cambios necesarios serán:
- Añadir una opción a la pantalla de Opciones, que nos permita elegir entre "Imagen fija" o "Imagen panorámica" en el home.
- En el caso de elegir "Imagen fija", esa misma vista nos permitirá subir la imagen que deseamos.
- En el caso de elegir "Imagen panorámica", desde esa misma vista podremos elegir y previsualizar qué escena queremos.
- Hay que quitar el checkbox "Portada" que actualmente aparece en la administración de escenas, ya que todo esto lo vamos a gestionar desde la pantalla de "Opciones"

**Comment by 7-carmen** [comment]
Ya esta cambiado el aspecto de la pantalla de Opciones, ahora estoy añadiendo la posibilidad de de elegir entre el tipo de imagen.

**Comment by 7-carmen** [comment]
Todo terminado, @mmarbonillo y yo estamos trabajando en la previsualización de la 360 y cerramos issue.
