### ISSUE TITLE
Insertar etiquetas meta

### ISSUE THREAD

**Issue by avozme** [mmarbonillo/celia-tour#86]
Hay que modificar el header de todas las páginas del frontpage para que incluyan el metatítulo y la metadescripción extraídos de la tabla de opciones.

Si se ve interesante añadir más etiquetas meta, habría que agregar la entrada correspondiente en el fomulario de opciones del panel de administración.

Estas etiquetas ya no influyen en el SEO, como antiguamente, pero Google las utiliza para mostrar una descripción de la página en sus resultados de búsqueda.

**Comment by 7-carmen** [comment]
Esta parte la tiene Ángel lista desde hace tiempo y la issue se quedo olvidada, cierro issue
